# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dashboard.ui'
#
# Created: Thu Apr 10 01:45:08 2014
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1256, 691)
        MainWindow.setMouseTracking(False)
        MainWindow.setAcceptDrops(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/pixmaps/cubeview48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setToolTip("")
        MainWindow.setAutoFillBackground(False)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graph = PlotWidget(self.centralwidget)
        self.graph.setGeometry(QtCore.QRect(0, 10, 881, 471))
        self.graph.setObjectName("graph")
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1110, 670, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.editedgraph = PlotWidget(self.centralwidget)
        self.editedgraph.setGeometry(QtCore.QRect(0, 490, 571, 201))
        self.editedgraph.setObjectName("editedgraph")
        self.files = QtGui.QComboBox(self.centralwidget)
        self.files.setGeometry(QtCore.QRect(890, 0, 371, 27))
        self.files.setObjectName("files")
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(618, 480, 41, 21))
        self.label_3.setObjectName("label_3")
        self.dIdVval = QtGui.QLabel(self.centralwidget)
        self.dIdVval.setGeometry(QtCore.QRect(668, 480, 151, 16))
        self.dIdVval.setText("")
        self.dIdVval.setObjectName("dIdVval")
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(618, 510, 41, 21))
        self.label_4.setObjectName("label_4")
        self.dVdIval = QtGui.QLabel(self.centralwidget)
        self.dVdIval.setGeometry(QtCore.QRect(668, 510, 151, 16))
        self.dVdIval.setText("")
        self.dVdIval.setObjectName("dVdIval")
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(790, 510, 98, 27))
        self.pushButton.setObjectName("pushButton")
        self.graph2 = PlotWidget(self.centralwidget)
        self.graph2.setGeometry(QtCore.QRect(680, 560, 201, 131))
        self.graph2.setObjectName("graph2")
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(680, 536, 201, 21))
        self.pushButton_2.setObjectName("pushButton_2")
        self.thumbs = QtGui.QListWidget(self.centralwidget)
        self.thumbs.setGeometry(QtCore.QRect(890, 30, 361, 631))
        self.thumbs.setAcceptDrops(True)
        self.thumbs.setDragEnabled(True)
        self.thumbs.setDragDropMode(QtGui.QAbstractItemView.NoDragDrop)
        self.thumbs.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.thumbs.setIconSize(QtCore.QSize(150, 300))
        self.thumbs.setFlow(QtGui.QListView.TopToBottom)
        self.thumbs.setResizeMode(QtGui.QListView.Adjust)
        self.thumbs.setViewMode(QtGui.QListView.ListMode)
        self.thumbs.setObjectName("thumbs")
        self.pushButton_3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(890, 666, 211, 21))
        self.pushButton_3.setObjectName("pushButton_3")
        self.filename = QtGui.QLineEdit(self.centralwidget)
        self.filename.setGeometry(QtCore.QRect(790, 480, 101, 27))
        self.filename.setObjectName("filename")
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionSave_as = QtGui.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL("clicked()"), MainWindow.saveplot)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL("clicked()"), MainWindow.generate_thumbnails)
        QtCore.QObject.connect(self.files, QtCore.SIGNAL("currentIndexChanged(QString)"), MainWindow.loadfile)
        QtCore.QObject.connect(self.pushButton_3, QtCore.SIGNAL("clicked()"), MainWindow.plot_selection)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "graph editing", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Author: Jithin B.P.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", " G =", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", " R =", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "saveplot", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("MainWindow", "regenerate thumbnails", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("MainWindow", "Plot selection", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_as.setText(QtGui.QApplication.translate("MainWindow", "Save as", None, QtGui.QApplication.UnicodeUTF8))

from pyqtgraph import PlotWidget
