# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dashboard.ui'
#
# Created: Sat Nov 23 23:57:28 2013
#      by: pyside-uic 0.2.13 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(999, 600)
        MainWindow.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/pixmaps/cubeview48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setToolTip("")
        MainWindow.setAutoFillBackground(False)
        MainWindow.setTabShape(QtGui.QTabWidget.Triangular)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.init_button = QtGui.QPushButton(self.centralwidget)
        self.init_button.setGeometry(QtCore.QRect(850, 430, 141, 27))
        self.init_button.setObjectName("init_button")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(15, 9, 270, 21))
        font = QtGui.QFont()
        font.setFamily("URW Chancery L")
        font.setPointSize(12)
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.IVgraph = PlotWidget(self.centralwidget)
        self.IVgraph.setGeometry(QtCore.QRect(10, 420, 301, 151))
        self.IVgraph.setObjectName("IVgraph")
        self.fetch_data = QtGui.QCheckBox(self.centralwidget)
        self.fetch_data.setGeometry(QtCore.QRect(680, 410, 141, 27))
        self.fetch_data.setChecked(True)
        self.fetch_data.setObjectName("fetch_data")
        self.total_readings = QtGui.QLabel(self.centralwidget)
        self.total_readings.setGeometry(QtCore.QRect(650, 10, 161, 16))
        self.total_readings.setObjectName("total_readings")
        self.Save_data = QtGui.QPushButton(self.centralwidget)
        self.Save_data.setGeometry(QtCore.QRect(460, 540, 71, 27))
        self.Save_data.setObjectName("Save_data")
        self.filename = QtGui.QLineEdit(self.centralwidget)
        self.filename.setGeometry(QtCore.QRect(320, 540, 131, 27))
        self.filename.setObjectName("filename")
        self.dIdVgraph = PlotWidget(self.centralwidget)
        self.dIdVgraph.setGeometry(QtCore.QRect(10, 30, 811, 381))
        self.dIdVgraph.setObjectName("dIdVgraph")
        self.pulse_width = QtGui.QSlider(self.centralwidget)
        self.pulse_width.setGeometry(QtCore.QRect(320, 410, 241, 29))
        self.pulse_width.setMinimum(100)
        self.pulse_width.setMaximum(2000)
        self.pulse_width.setSingleStep(5)
        self.pulse_width.setProperty("value", 100)
        self.pulse_width.setOrientation(QtCore.Qt.Horizontal)
        self.pulse_width.setTickPosition(QtGui.QSlider.TicksBelow)
        self.pulse_width.setTickInterval(1000)
        self.pulse_width.setObjectName("pulse_width")
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(560, 410, 111, 31))
        self.label_2.setObjectName("label_2")
        self.pw_label = QtGui.QLabel(self.centralwidget)
        self.pw_label.setGeometry(QtCore.QRect(590, 430, 51, 17))
        self.pw_label.setObjectName("pw_label")
        self.state = QtGui.QPushButton(self.centralwidget)
        self.state.setGeometry(QtCore.QRect(850, 480, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.state.setFont(font)
        self.state.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.state.setObjectName("state")
        self.nvpr = QtGui.QLabel(self.centralwidget)
        self.nvpr.setGeometry(QtCore.QRect(860, 550, 121, 21))
        self.nvpr.setAutoFillBackground(True)
        self.nvpr.setObjectName("nvpr")
        self.IVfit = QtGui.QLabel(self.centralwidget)
        self.IVfit.setGeometry(QtCore.QRect(540, 530, 281, 20))
        self.IVfit.setObjectName("IVfit")
        self.v5 = QtGui.QRadioButton(self.centralwidget)
        self.v5.setGeometry(QtCore.QRect(380, 490, 71, 22))
        self.v5.setObjectName("v5")
        self.v1 = QtGui.QRadioButton(self.centralwidget)
        self.v1.setGeometry(QtCore.QRect(320, 460, 60, 22))
        self.v1.setChecked(False)
        self.v1.setObjectName("v1")
        self.v2 = QtGui.QRadioButton(self.centralwidget)
        self.v2.setGeometry(QtCore.QRect(380, 460, 71, 22))
        self.v2.setObjectName("v2")
        self.v4 = QtGui.QRadioButton(self.centralwidget)
        self.v4.setGeometry(QtCore.QRect(320, 490, 71, 22))
        self.v4.setObjectName("v4")
        self.v3 = QtGui.QRadioButton(self.centralwidget)
        self.v3.setGeometry(QtCore.QRect(450, 460, 81, 22))
        self.v3.setChecked(True)
        self.v3.setObjectName("v3")
        self.v6 = QtGui.QRadioButton(self.centralwidget)
        self.v6.setGeometry(QtCore.QRect(450, 490, 71, 22))
        self.v6.setObjectName("v6")
        self.progress = QtGui.QProgressBar(self.centralwidget)
        self.progress.setGeometry(QtCore.QRect(850, 410, 141, 16))
        self.progress.setProperty("value", 0)
        self.progress.setObjectName("progress")
        self.lcdNumber = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(680, 440, 111, 23))
        self.lcdNumber.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lcdNumber.setSmallDecimalPoint(True)
        self.lcdNumber.setNumDigits(10)
        self.lcdNumber.setObjectName("lcdNumber")
        self.dIdVfit = QtGui.QLabel(self.centralwidget)
        self.dIdVfit.setGeometry(QtCore.QRect(540, 550, 281, 17))
        self.dIdVfit.setObjectName("dIdVfit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 999, 25))
        self.menubar.setObjectName("menubar")
        self.menuSave = QtGui.QMenu(self.menubar)
        self.menuSave.setObjectName("menuSave")
        MainWindow.setMenuBar(self.menubar)
        self.actionSave_as = QtGui.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.menubar.addAction(self.menuSave.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.init_button, QtCore.SIGNAL("clicked()"), MainWindow.start_measuring)
        QtCore.QObject.connect(self.Save_data, QtCore.SIGNAL("clicked()"), MainWindow.dump_to_file)
        QtCore.QObject.connect(self.pulse_width, QtCore.SIGNAL("sliderMoved(int)"), self.pw_label.setNum)
        QtCore.QObject.connect(self.pulse_width, QtCore.SIGNAL("sliderReleased()"), MainWindow.set_pulse_width)
        QtCore.QObject.connect(self.v1, QtCore.SIGNAL("clicked()"), MainWindow.set_vc)
        QtCore.QObject.connect(self.v4, QtCore.SIGNAL("clicked()"), MainWindow.set_vc)
        QtCore.QObject.connect(self.v2, QtCore.SIGNAL("clicked()"), MainWindow.set_vc)
        QtCore.QObject.connect(self.v5, QtCore.SIGNAL("clicked()"), MainWindow.set_vc)
        QtCore.QObject.connect(self.v3, QtCore.SIGNAL("clicked()"), MainWindow.set_vc)
        QtCore.QObject.connect(self.v6, QtCore.SIGNAL("clicked()"), MainWindow.set_vc)
        QtCore.QObject.connect(self.state, QtCore.SIGNAL("clicked()"), MainWindow.toggle_state)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "PCAR Spectroscopy", None, QtGui.QApplication.UnicodeUTF8))
        self.init_button.setText(QtGui.QApplication.translate("MainWindow", "Start measurements", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Point Contact Andreev Reflection Spectroscopy", None, QtGui.QApplication.UnicodeUTF8))
        self.fetch_data.setText(QtGui.QApplication.translate("MainWindow", "Get readings", None, QtGui.QApplication.UnicodeUTF8))
        self.total_readings.setText(QtGui.QApplication.translate("MainWindow", "Loaded readings = ", None, QtGui.QApplication.UnicodeUTF8))
        self.Save_data.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.filename.setText(QtGui.QApplication.translate("MainWindow", "datafile", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Pulse Width(uS)", None, QtGui.QApplication.UnicodeUTF8))
        self.pw_label.setText(QtGui.QApplication.translate("MainWindow", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.state.setText(QtGui.QApplication.translate("MainWindow", "ARM", None, QtGui.QApplication.UnicodeUTF8))
        self.nvpr.setText(QtGui.QApplication.translate("MainWindow", "   nanovoltmeter", None, QtGui.QApplication.UnicodeUTF8))
        self.IVfit.setText(QtGui.QApplication.translate("MainWindow", "V = ", None, QtGui.QApplication.UnicodeUTF8))
        self.v5.setText(QtGui.QApplication.translate("MainWindow", "10V", None, QtGui.QApplication.UnicodeUTF8))
        self.v1.setText(QtGui.QApplication.translate("MainWindow", "1mV", None, QtGui.QApplication.UnicodeUTF8))
        self.v2.setText(QtGui.QApplication.translate("MainWindow", "10mV", None, QtGui.QApplication.UnicodeUTF8))
        self.v4.setText(QtGui.QApplication.translate("MainWindow", "1V", None, QtGui.QApplication.UnicodeUTF8))
        self.v3.setText(QtGui.QApplication.translate("MainWindow", "100mV", None, QtGui.QApplication.UnicodeUTF8))
        self.v6.setText(QtGui.QApplication.translate("MainWindow", "100V", None, QtGui.QApplication.UnicodeUTF8))
        self.dIdVfit.setText(QtGui.QApplication.translate("MainWindow", "dI/dV =", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSave.setTitle(QtGui.QApplication.translate("MainWindow", "PCAR", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_as.setText(QtGui.QApplication.translate("MainWindow", "Save as", None, QtGui.QApplication.UnicodeUTF8))

from pyqtgraph import PlotWidget
